/**
 * Setor: Sucesso do Cliente (Customer Success)
 * Fonte: "Competências Plano de Carreira sucesso ao cliente.xlsx".
 *
 * Este setor tem 4 níveis (Analista Jr/Pleno/Sênior e Supervisor — sem Coordenador),
 * mesmo padrão do Suporte Técnico e da Produção.
 *
 * EDITE ESTE ARQUIVO PARA ATUALIZAR CARGOS, PERGUNTAS, PESOS E CONTEÚDO DA BIBLIOTECA
 * DE PLANO DE CARREIRA DESTE SETOR. Nenhuma alteração aqui afeta outros setores.
 */

const SETOR_SUCESSO_CLIENTE = {
  id: "sucesso-cliente",
  nome: "Sucesso do Cliente",

  visaoGeral: {
    objetivo:
      "A área de Sucesso do Cliente (Customer Success) acompanha a jornada dos clientes ICOM TV após a venda, " +
      "garantindo que obtenham valor real das soluções contratadas, monitorando indicadores como Health Score, " +
      "NPS, CSAT e Churn para maximizar retenção e fidelização.",
    responsabilidades: [
      "Acompanhamento consultivo e preventivo da carteira de clientes, identificando riscos de cancelamento (churn).",
      "Elaboração e execução de Planos de Sucesso personalizados para clientes estratégicos.",
      "Identificação de oportunidades de expansão de conta (upsell/cross-sell) em parceria com o Comercial.",
      "Integração com Relacionamento, Comercial, Produção e Suporte para uma jornada completa do cliente.",
    ],
    importancia:
      "A retenção e a satisfação medidas por indicadores como Churn, NPS e Health Score dependem diretamente da " +
      "atuação preventiva deste time — cancelamentos evitáveis e clientes inativos representam perda direta de " +
      "receita para a ICOM TV.",
    competenciasValorizadas: ["Relacionamento", "Análise", "Gestão", "Comunicação", "Estratégia"],
  },

  cargos: [
    {
      id: "jr",
      ordem: 1,
      nome: "Analista de Sucesso do Cliente Júnior",
      objetivo:
        "O Analista de Sucesso do Cliente Júnior é responsável por acompanhar a jornada dos clientes da ICOM TV, " +
        "garantindo que obtenham o máximo valor da solução e alcancem os resultados esperados. Atua de forma " +
        "preventiva, identificando riscos, oportunidades de melhoria e necessidades dos clientes, promovendo ações " +
        "que aumentem o engajamento, fortaleçam o relacionamento e reduzam o índice de cancelamentos. Seu objetivo " +
        "é contribuir para uma experiência positiva, aumentando a satisfação, a retenção e a fidelização dos " +
        "clientes.",
      competenciasEsperadas: [],
      responsabilidades: [
        "Acompanhar a carteira de clientes, monitorando indicadores de utilização, engajamento e satisfação.",
        "Realizar contatos periódicos para acompanhar a evolução dos clientes e identificar possíveis necessidades.",
        "Atuar preventivamente em clientes com sinais de risco de cancelamento (churn).",
        "Auxiliar clientes na melhor utilização dos serviços e funcionalidades da ICOM TV.",
        "Identificar oportunidades de melhoria na experiência do cliente e direcioná-las aos setores responsáveis.",
        "Registrar todas as interações e planos de ação no CRM e sistemas internos.",
        "Apoiar na elaboração de planos de sucesso para clientes com baixo engajamento.",
        "Trabalhar em conjunto com Relacionamento, Comercial, Produção e Suporte para solucionar necessidades dos clientes.",
        "Acompanhar clientes durante períodos de adaptação ou mudanças importantes.",
        "Auxiliar em ações de retenção, recuperação de clientes e fortalecimento do relacionamento.",
        "Coletar feedbacks dos clientes para contribuir com melhorias nos produtos, processos e serviços.",
        "Cumprir os processos internos e indicadores definidos para a área.",
      ],
      indicadores: {
        aumentar: [
          "O engajamento dos clientes com a ICOM TV.",
          "A satisfação dos clientes.",
          "A utilização das soluções contratadas.",
          "A percepção de valor da plataforma.",
          "O relacionamento de longo prazo.",
        ],
        garantir: [
          "Atendimento consultivo e humanizado.",
          "Acompanhamento preventivo dos clientes.",
          "Registro correto das informações.",
          "Cumprimento dos processos da área.",
          "Comunicação clara e objetiva.",
        ],
        reduzir: [
          "Cancelamentos evitáveis.",
          "Clientes inativos.",
          "Reclamações recorrentes.",
          "Dificuldades de utilização da plataforma.",
          "Atritos na jornada do cliente.",
        ],
      },
      conhecimentosTecnicos: [],
      comportamentosEsperados: [
        "Empatia.",
        "Comunicação clara e assertiva.",
        "Escuta ativa.",
        "Inteligência emocional.",
        "Organização.",
        "Gestão do tempo.",
        "Proatividade.",
        "Pensamento analítico.",
        "Facilidade para resolver problemas.",
        "Trabalho em equipe.",
        "Adaptabilidade.",
        "Responsabilidade.",
        "Comprometimento.",
        "Capacidade de negociação.",
        "Orientação para resultados.",
        "Foco no cliente.",
        "Aprendizado contínuo.",
      ],
      formacaoAcademica: "Ensino Superior cursando ou concluído em Administração, Marketing, Gestão Comercial, Comunicação Social, Publicidade e Propaganda, Processos Gerenciais ou áreas correlatas. Cursos relacionados à Experiência do Cliente (CX), Customer Success, Atendimento ou Vendas Consultivas serão considerados diferenciais.",
      tempoMinimoPromocao: "1 ano",
      provaConhecimentos: false,
    },
    {
      id: "pl",
      ordem: 2,
      nome: "Analista de Sucesso do Cliente Pleno",
      objetivo:
        "O Analista de Sucesso do Cliente Pleno é responsável por gerenciar estrategicamente sua carteira de " +
        "clientes, garantindo que obtenham resultados concretos com as soluções da ICOM TV. Atua de forma " +
        "consultiva e preventiva, identificando oportunidades de expansão, fortalecendo o relacionamento, reduzindo " +
        "riscos de cancelamento e conduzindo planos de sucesso personalizados. Além disso, contribui para a " +
        "melhoria dos processos internos e compartilha conhecimento com os profissionais mais juniores da equipe.",
      competenciasEsperadas: [],
      responsabilidades: [
        "Gerenciar uma carteira de clientes de forma estratégica, acompanhando indicadores de saúde, utilização e satisfação.",
        "Desenvolver e executar Planos de Sucesso personalizados para clientes estratégicos.",
        "Realizar reuniões periódicas para apresentação de resultados, identificação de oportunidades e definição de ações.",
        "Atuar preventivamente na redução do churn, identificando clientes em risco e conduzindo planos de recuperação.",
        "Identificar oportunidades de expansão da conta (upsell, cross-sell e novas soluções), encaminhando-as ao Comercial quando necessário.",
        "Analisar indicadores como Health Score, NPS, CSAT, taxa de utilização e retenção para tomada de decisão.",
        "Trabalhar em conjunto com Relacionamento, Comercial, Produção, Suporte e Marketing para garantir uma experiência integrada ao cliente.",
        "Atuar na resolução de casos de média e alta complexidade, buscando soluções rápidas e sustentáveis.",
        "Conduzir negociações de retenção dentro das políticas da empresa.",
        "Coletar feedbacks estruturados dos clientes e transformá-los em oportunidades de melhoria para produtos e processos.",
        "Apoiar o desenvolvimento técnico dos Analistas Juniores, compartilhando boas práticas e orientações.",
        "Participar da construção e melhoria dos processos da área de Customer Success.",
      ],
      indicadores: {
        aumentar: [
          "A retenção da carteira de clientes.",
          "O nível de engajamento com as soluções da ICOM TV.",
          "A percepção de valor do serviço.",
          "O índice de satisfação dos clientes.",
          "As oportunidades de expansão de receita.",
        ],
        garantir: [
          "Acompanhamento consultivo e estratégico.",
          "Execução dos Planos de Sucesso.",
          "Comunicação clara e transparente.",
          "Cumprimento dos indicadores da área.",
          "Excelente experiência ao cliente.",
        ],
        reduzir: [
          "Cancelamentos.",
          "Clientes inativos.",
          "Reclamações recorrentes.",
          "Baixo engajamento.",
          "Tempo de resolução de situações críticas.",
        ],
      },
      conhecimentosTecnicos: [
        "CRM e plataformas de gestão de clientes.",
        "Pacote Office intermediário (Excel, PowerPoint e Word).",
        "Customer Success.",
        "Customer Experience (CX).",
        "Jornada do Cliente.",
        "Health Score.",
        "NPS, CSAT e indicadores de retenção.",
        "Técnicas de retenção e negociação.",
        "Gestão de carteira.",
        "Noções de vendas consultivas e expansão de contas.",
        "Capacidade analítica para interpretação de indicadores.",
      ],
      comportamentosEsperados: [
        "Comunicação consultiva.",
        "Escuta ativa.",
        "Empatia.",
        "Inteligência emocional.",
        "Organização.",
        "Gestão do tempo.",
        "Pensamento analítico.",
        "Proatividade.",
        "Capacidade de negociação.",
        "Resolução de problemas.",
        "Adaptabilidade.",
        "Trabalho em equipe.",
        "Influência positiva.",
        "Orientação para resultados.",
        "Foco na experiência do cliente.",
        "Aprendizado contínuo.",
      ],
      formacaoAcademica: "Ensino Superior completo ou em fase final de conclusão em Administração, Marketing, Gestão Comercial, Comunicação Social, Publicidade e Propaganda, Processos Gerenciais ou áreas correlatas. Será considerado diferencial possuir certificações em Customer Success, Customer Experience (CX), Negociação, Gestão de Clientes ou Sucesso do Cliente.",
      tempoMinimoPromocao: "1 ano e 6 meses",
      provaConhecimentos: true,
    },
    {
      id: "sr",
      ordem: 3,
      nome: "Analista de Sucesso do Cliente Sênior",
      objetivo:
        "O Analista de Sucesso do Cliente Sênior é responsável por conduzir estrategicamente a jornada dos clientes " +
        "mais relevantes da ICOM TV, garantindo retenção, fidelização, geração de valor e crescimento sustentável " +
        "da carteira. Atua como referência técnica da equipe, liderando ações de recuperação de clientes em risco, " +
        "desenvolvendo estratégias de retenção, apoiando a evolução dos processos internos e promovendo uma " +
        "experiência de excelência. Sua atuação influencia diretamente os indicadores de churn, satisfação, " +
        "expansão e sucesso dos clientes.",
      competenciasEsperadas: [
        "Experiência consolidada em Customer Success, Pós-venda, Gestão de Contas ou Retenção.",
        "Vivência na gestão de clientes estratégicos e negociações complexas.",
        "Experiência com indicadores de sucesso do cliente e análise de resultados.",
        "Experiência em apoio técnico e desenvolvimento de equipes.",
      ],
      responsabilidades: [
        "Gerenciar a carteira de clientes estratégicos e de maior complexidade da empresa.",
        "Elaborar e conduzir Planos de Sucesso personalizados para clientes com maior potencial ou risco.",
        "Liderar negociações de retenção em situações críticas, buscando preservar o relacionamento e a receita da empresa.",
        "Atuar de forma preventiva na identificação de riscos de churn, desenvolvendo estratégias para reversão e fidelização.",
        "Realizar reuniões executivas com clientes para apresentação de resultados, oportunidades e planos de evolução.",
        "Analisar indicadores como Health Score, NPS, CSAT, retenção, utilização da plataforma e engajamento para definição de estratégias.",
        "Identificar oportunidades de expansão da carteira (upsell e cross-sell) e atuar em conjunto com o Comercial para sua concretização.",
        "Atuar como referência técnica da equipe, apoiando Analistas Juniores e Plenos na resolução de casos complexos.",
        "Participar da criação, revisão e padronização dos processos da área de Customer Success.",
        "Desenvolver materiais, treinamentos e boas práticas para fortalecimento da equipe.",
        "Coletar e consolidar feedbacks estratégicos dos clientes, propondo melhorias para produtos, serviços e processos internos.",
        "Trabalhar de forma integrada com Relacionamento, Comercial, Produção, Suporte, Marketing e demais áreas para garantir uma experiência completa ao cliente.",
        "Apoiar a liderança no acompanhamento dos indicadores da área e na definição de planos de ação.",
      ],
      indicadores: {
        aumentar: [
          "A retenção dos clientes estratégicos.",
          "A satisfação e fidelização da carteira.",
          "O engajamento e utilização das soluções da ICOM TV.",
          "As oportunidades de expansão de receita.",
          "A maturidade da equipe de Customer Success.",
          "A percepção de valor da marca ICOM TV.",
        ],
        garantir: [
          "Relacionamentos duradouros e de confiança com os clientes.",
          "Atendimento consultivo e estratégico.",
          "Alta qualidade na execução dos Planos de Sucesso.",
          "Desenvolvimento técnico dos analistas da equipe.",
          "Integração entre os setores envolvidos na jornada do cliente.",
          "Cumprimento dos indicadores estratégicos da área.",
        ],
        reduzir: [
          "Churn.",
          "Reclamações recorrentes.",
          "Clientes inativos ou com baixo engajamento.",
          "Tempo de resolução de situações críticas.",
          "Retrabalho entre as áreas.",
          "Perda de oportunidades de retenção e expansão.",
        ],
      },
      conhecimentosTecnicos: [
        "Gestão estratégica de Customer Success.",
        "Gestão de carteira de clientes.",
        "CRM e plataformas de Customer Success.",
        "Health Score, NPS, CSAT, Churn Rate e indicadores de retenção.",
        "Técnicas avançadas de retenção e negociação.",
        "Customer Experience (CX).",
        "Jornada do Cliente.",
        "Análise de indicadores e elaboração de planos de ação.",
        "Pacote Office intermediário/avançado (principalmente Excel e PowerPoint).",
        "Técnicas de apresentação executiva.",
        "Noções de vendas consultivas e expansão de contas.",
      ],
      comportamentosEsperados: [
        "Liderança técnica.",
        "Comunicação consultiva.",
        "Escuta ativa.",
        "Inteligência emocional.",
        "Empatia.",
        "Pensamento estratégico.",
        "Capacidade analítica.",
        "Organização.",
        "Gestão do tempo.",
        "Resolução de problemas.",
        "Negociação.",
        "Proatividade.",
        "Influência positiva.",
        "Desenvolvimento de pessoas.",
        "Adaptabilidade.",
        "Trabalho em equipe.",
        "Orientação para resultados.",
        "Foco na experiência do cliente.",
        "Visão sistêmica.",
        "Aprendizado contínuo.",
      ],
      formacaoAcademica: "Ensino Superior completo em Administração, Marketing, Gestão Comercial, Comunicação Social, Publicidade e Propaganda, Processos Gerenciais ou áreas correlatas. Será considerado diferencial possuir Pós-graduação ou certificações em Customer Success, Customer Experience (CX), Gestão de Negócios, Liderança, Negociação ou Gestão de Relacionamento.",
      tempoMinimoPromocao: "2 Anos",
      provaConhecimentos: true,
    },
    {
      id: "sup",
      ordem: 4,
      nome: "Supervisor de Sucesso do Cliente",
      objetivo:
        "O Supervisor de Sucesso do Cliente é responsável por liderar a equipe de Customer Success da ICOM TV, " +
        "garantindo que os clientes alcancem resultados consistentes com as soluções da empresa e que a operação " +
        "entregue altos índices de retenção, satisfação e fidelização. Atua na gestão de pessoas, indicadores e " +
        "processos, promovendo uma cultura de atendimento consultivo, melhoria contínua e foco no sucesso do " +
        "cliente. Além disso, acompanha clientes estratégicos e situações críticas, apoiando a equipe na tomada de " +
        "decisões e na construção de relacionamentos de longo prazo.",
      competenciasEsperadas: [
        "Experiência consolidada em Customer Success, Gestão de Contas ou Retenção.",
        "Experiência em liderança de equipes.",
        "Vivência na gestão de indicadores estratégicos.",
        "Experiência em negociação e recuperação de clientes.",
        "Gestão de processos e melhoria contínua.",
      ],
      responsabilidades: [
        "Liderar, acompanhar e desenvolver a equipe de Sucesso do Cliente.",
        "Definir prioridades da operação e distribuir as carteiras de clientes de forma estratégica.",
        "Monitorar indicadores da área, como Churn, Retenção, NPS, CSAT, Health Score, tempo de resposta e engajamento dos clientes.",
        "Realizar reuniões individuais e coletivas de acompanhamento, desenvolvimento e feedback da equipe.",
        "Apoiar os analistas na condução de negociações de retenção e casos de alta complexidade.",
        "Desenvolver planos de ação para redução do churn e aumento da retenção da base de clientes.",
        "Garantir que todos os clientes estratégicos possuam planos de sucesso e acompanhamento contínuo.",
        "Trabalhar em conjunto com Comercial, Relacionamento, Produção, Suporte e Marketing para promover uma jornada integrada do cliente.",
        "Identificar oportunidades de expansão da carteira e alinhar estratégias com o setor Comercial.",
        "Estruturar, revisar e otimizar processos internos da área de Customer Success.",
        "Elaborar indicadores, relatórios gerenciais e apresentações para a Coordenação e Diretoria.",
        "Promover treinamentos técnicos e comportamentais para o desenvolvimento da equipe.",
        "Garantir a padronização dos processos, registros e atendimentos realizados pelo setor.",
        "Disseminar a cultura Customer Centric dentro da empresa.",
        "Liderar projetos voltados à melhoria da experiência do cliente.",
      ],
      indicadores: {
        aumentar: [
          "A taxa de retenção dos clientes.",
          "O Health Score médio da carteira.",
          "O NPS e CSAT da empresa.",
          "O engajamento dos clientes com as soluções da ICOM TV.",
          "O desenvolvimento técnico da equipe.",
          "A produtividade da operação.",
          "A identificação de oportunidades de expansão da carteira.",
        ],
        garantir: [
          "Atendimento consultivo de excelência.",
          "Cumprimento dos indicadores da área.",
          "Execução eficiente dos Planos de Sucesso.",
          "Padronização dos processos.",
          "Integração entre Customer Success e os demais setores.",
          "Desenvolvimento contínuo da equipe.",
          "Excelente experiência durante toda a jornada do cliente.",
        ],
        reduzir: [
          "Churn.",
          "Cancelamentos evitáveis.",
          "Reclamações recorrentes.",
          "Clientes inativos.",
          "Tempo de resolução de problemas críticos.",
          "Retrabalho operacional.",
          "Falhas de comunicação entre áreas.",
        ],
      },
      conhecimentosTecnicos: [
        "Gestão de Customer Success.",
        "Gestão de indicadores (KPIs).",
        "Churn Rate.",
        "Retenção de clientes.",
        "Health Score.",
        "NPS e CSAT.",
        "Jornada do Cliente.",
        "Customer Experience (CX).",
        "CRM e plataformas de gestão de clientes.",
        "Gestão de processos.",
        "Planejamento estratégico.",
        "Técnicas avançadas de negociação.",
        "Gestão de equipes.",
        "Pacote Office intermediário/avançado, com domínio de Excel para análise de indicadores.",
      ],
      comportamentosEsperados: [
        "Liderança.",
        "Inteligência emocional.",
        "Comunicação assertiva.",
        "Escuta ativa.",
        "Empatia.",
        "Pensamento estratégico.",
        "Visão sistêmica.",
        "Capacidade analítica.",
        "Organização.",
        "Gestão do tempo.",
        "Desenvolvimento de pessoas.",
        "Gestão de conflitos.",
        "Influência positiva.",
        "Proatividade.",
        "Adaptabilidade.",
        "Tomada de decisão.",
        "Orientação para resultados.",
        "Foco na experiência do cliente.",
        "Melhoria contínua.",
        "Trabalho em equipe.",
      ],
      formacaoAcademica: "Ensino Superior completo em Administração, Marketing, Gestão Comercial, Comunicação Social, Publicidade e Propaganda, Processos Gerenciais ou áreas correlatas. Será considerado diferencial possuir Pós-graduação ou MBA em Gestão de Pessoas, Customer Success, Customer Experience (CX), Gestão de Negócios, Liderança ou áreas relacionadas.",
      tempoMinimoPromocao: null,
      provaConhecimentos: true,
    },
  ],

  // pesos: { jr, pl, sr, sup } — 0 a 3 (este setor não possui nível Coordenador)
  questions: [
    { id: "sc1",  texto: "Identifico sinais de risco de cancelamento (churn) antes que o cliente decida sair.", categoria: "analise", pesos: { jr: 2, pl: 3, sr: 3, sup: 1 } },
    { id: "sc2",  texto: "Analiso indicadores como Health Score, NPS ou CSAT para entender a saúde de uma conta.", categoria: "analise", pesos: { jr: 1, pl: 2, sr: 3, sup: 3 } },
    { id: "sc3",  texto: "Consigo identificar padrões em contas com baixo engajamento antes que isso vire um problema.", categoria: "analise", pesos: { jr: 1, pl: 2, sr: 3, sup: 2 } },
    { id: "sc4",  texto: "Construo relações de confiança de longo prazo com os clientes da minha carteira.", categoria: "relacionamento", pesos: { jr: 2, pl: 3, sr: 3, sup: 1 } },
    { id: "sc5",  texto: "Conduzo reuniões consultivas apresentando resultados e oportunidades ao cliente, não só resolvendo problemas.", categoria: "relacionamento", pesos: { jr: 1, pl: 2, sr: 3, sup: 1 } },
    { id: "sc6",  texto: "Sou referência de relacionamento para os clientes mais estratégicos da carteira.", categoria: "relacionamento", pesos: { jr: 0, pl: 1, sr: 3, sup: 2 } },
    { id: "sc7",  texto: "Conduzo negociações de retenção com clientes em risco de cancelamento com autonomia.", categoria: "autonomia", pesos: { jr: 0, pl: 2, sr: 3, sup: 2 } },
    { id: "sc8",  texto: "Assumo a responsabilidade por recuperar um cliente insatisfeito antes que ele cancele.", categoria: "autonomia", pesos: { jr: 1, pl: 2, sr: 3, sup: 2 } },
    { id: "sc9",  texto: "Cumpro prazos de acompanhamento da carteira mesmo com alto volume de clientes.", categoria: "autonomia", pesos: { jr: 2, pl: 2, sr: 2, sup: 1 } },
    { id: "sc10", texto: "Identifico oportunidades de upsell ou cross-sell na minha carteira e encaminho ao Comercial.", categoria: "estrategia", pesos: { jr: 0, pl: 2, sr: 3, sup: 2 } },
    { id: "sc11", texto: "Penso na jornada completa do cliente, não apenas na demanda pontual que estou resolvendo.", categoria: "estrategia", pesos: { jr: 1, pl: 2, sr: 3, sup: 3 } },
    { id: "sc12", texto: "Participo do planejamento estratégico de metas e indicadores da área.", categoria: "estrategia", pesos: { jr: 0, pl: 0, sr: 1, sup: 3 } },
    { id: "sc13", texto: "Oriento colegas juniores sobre como conduzir uma negociação de retenção.", categoria: "lideranca", pesos: { jr: 0, pl: 1, sr: 3, sup: 2 } },
    { id: "sc14", texto: "Aplico feedbacks estruturados e acompanho planos de desenvolvimento individual da equipe.", categoria: "lideranca", pesos: { jr: 0, pl: 0, sr: 1, sup: 3 } },
    { id: "sc15", texto: "Desenvolvo treinamentos técnicos e comportamentais para a equipe de Customer Success.", categoria: "lideranca", pesos: { jr: 0, pl: 0, sr: 1, sup: 3 } },
    { id: "sc16", texto: "Acompanho meus indicadores de retenção e satisfação regularmente, não só quando cobrado.", categoria: "gestao", pesos: { jr: 1, pl: 2, sr: 2, sup: 3 } },
    { id: "sc17", texto: "Uso dados de churn e cancelamentos para identificar onde a operação precisa melhorar.", categoria: "gestao", pesos: { jr: 0, pl: 1, sr: 2, sup: 3 } },
    { id: "sc18", texto: "Monitoro o cumprimento de indicadores de toda a equipe, não só da minha carteira.", categoria: "gestao", pesos: { jr: 0, pl: 0, sr: 1, sup: 3 } },

    { id: "sc19", texto: "Comunico de forma clara e transparente quando um cliente não terá uma demanda atendida no prazo esperado.", categoria: "comunicacao", pesos: { jr: 1, pl: 2, sr: 2, sup: 2 } },
    { id: "sc20", texto: "Documento planos de sucesso e interações no CRM de forma clara para outros colegas entenderem.", categoria: "comunicacao", pesos: { jr: 2, pl: 2, sr: 2, sup: 1 } },
    { id: "sc21", texto: "Represento a área de Sucesso do Cliente em reuniões com outros setores ou lideranças.", categoria: "comunicacao", pesos: { jr: 0, pl: 0, sr: 1, sup: 3 } },
    { id: "sc22", texto: "Trabalho de forma integrada com Relacionamento, Comercial, Produção e Suporte para resolver necessidades do cliente.", categoria: "relacionamento", pesos: { jr: 2, pl: 2, sr: 2, sup: 2 } },
    { id: "sc23", texto: "Ajudo a resolver problemas que envolvem mais de um setor na jornada do cliente.", categoria: "relacionamento", pesos: { jr: 0, pl: 1, sr: 2, sup: 3 } },
    { id: "sc24", texto: "Registro corretamente todas as interações e planos de ação no CRM e sistemas internos.", categoria: "organizacao", pesos: { jr: 3, pl: 2, sr: 2, sup: 1 } },
    { id: "sc25", texto: "Consigo gerenciar uma carteira grande de clientes sem perder o acompanhamento de nenhum.", categoria: "organizacao", pesos: { jr: 2, pl: 3, sr: 2, sup: 1 } },
    { id: "sc26", texto: "Priorizo minha carteira de forma estratégica, dando mais atenção às contas de maior risco ou potencial.", categoria: "organizacao", pesos: { jr: 1, pl: 2, sr: 3, sup: 2 } },
    { id: "sc27", texto: "Já propus uma melhoria de processo que reduziu o churn ou aumentou a retenção da equipe.", categoria: "inovacao", pesos: { jr: 0, pl: 1, sr: 3, sup: 3 } },
    { id: "sc28", texto: "Coleto feedbacks de clientes e transformo em sugestões de melhoria para produtos ou processos.", categoria: "inovacao", pesos: { jr: 1, pl: 2, sr: 2, sup: 2 } },

    { id: "sc29", texto: "Questiono processos existentes de acompanhamento buscando formas mais eficientes de reter clientes.", categoria: "inovacao", pesos: { jr: 0, pl: 1, sr: 2, sup: 3 } },
    { id: "sc30", texto: "Tomo decisões rápidas em uma negociação de retenção mesmo sob pressão de tempo.", categoria: "analise", pesos: { jr: 0, pl: 2, sr: 3, sup: 2 } },
    { id: "sc31", texto: "Avalio diferentes estratégias de retenção antes de escolher a mais adequada para cada cliente.", categoria: "analise", pesos: { jr: 1, pl: 2, sr: 3, sup: 2 } },
    { id: "sc32", texto: "Assumo a responsabilidade quando um cliente da minha carteira cancela, buscando entender o que faltou.", categoria: "autonomia", pesos: { jr: 1, pl: 2, sr: 2, sup: 2 } },
    { id: "sc33", texto: "Atuo de forma preventiva, identificando riscos antes que o cliente sinalize insatisfação.", categoria: "autonomia", pesos: { jr: 1, pl: 3, sr: 3, sup: 1 } },
    { id: "sc34", texto: "Pratico escuta ativa para entender as reais necessidades do cliente antes de propor soluções.", categoria: "comunicacao", pesos: { jr: 2, pl: 2, sr: 2, sup: 1 } },
    { id: "sc35", texto: "Adapto minha comunicação de acordo com o perfil de cada cliente da minha carteira.", categoria: "comunicacao", pesos: { jr: 2, pl: 2, sr: 2, sup: 1 } },
    { id: "sc36", texto: "Sei gerenciar uma situação crítica com um cliente estratégico prestes a cancelar.", categoria: "gestao", pesos: { jr: 0, pl: 1, sr: 3, sup: 2 } },
    { id: "sc37", texto: "Defino prioridades e distribuo carteiras de clientes entre a equipe de forma estratégica.", categoria: "gestao", pesos: { jr: 0, pl: 0, sr: 1, sup: 3 } },
    { id: "sc38", texto: "Ajudo a disseminar uma cultura de foco no cliente (Customer Centric) entre os colegas da equipe.", categoria: "lideranca", pesos: { jr: 0, pl: 1, sr: 2, sup: 3 } },
    { id: "sc39", texto: "Contribuo para reduzir a rotatividade e aumentar o engajamento da equipe de Sucesso do Cliente.", categoria: "lideranca", pesos: { jr: 0, pl: 0, sr: 1, sup: 3 } },
    { id: "sc40", texto: "Consigo apresentar resultados e planos de evolução de forma executiva para clientes estratégicos.", categoria: "analise", pesos: { jr: 0, pl: 1, sr: 3, sup: 2 } },
  ],

  recomendacoesPorCategoria: {
    comunicacao: "Pratique a escuta ativa e documente planos de sucesso de forma clara para que outros colegas consigam dar continuidade.",
    lideranca: "Ofereça-se para orientar colegas juniores em negociações de retenção e compartilhe boas práticas com a equipe.",
    organizacao: "Priorize sua carteira de forma estratégica e mantenha o CRM sempre atualizado com as interações realizadas.",
    estrategia: "Pense na jornada completa do cliente e busque identificar oportunidades de expansão de conta, não só resolver demandas pontuais.",
    analise: "Aprofunde a análise de indicadores como Health Score, NPS e CSAT para antecipar riscos de churn.",
    relacionamento: "Fortaleça a integração com Relacionamento, Comercial, Produção e Suporte nas demandas que envolvem mais de um setor.",
    gestao: "Acompanhe indicadores de churn e retenção com mais regularidade, usando dados para embasar suas ações.",
    autonomia: "Assuma negociações de retenção mais complexas sem esperar validação constante da liderança.",
    inovacao: "Proponha melhorias de processo baseadas em padrões de cancelamento ou baixo engajamento que você identifica no dia a dia.",
  },
};
